export const SHOW_PROPERTY = 'SHOW_PROPERTY'
export const CLOSE_PROPERTY = 'CLOSE_PROPERTY'
export const SELECT_PROERTY_CLASS = 'SELECT_PROERTY_CLASS'
export const SHOW_PARENT_CLASSES_URI = 'SHOW_PARENT_CLASSES_URI'
export const FOCUS_CIRCLE_KEY = 'FOCUS_CIRCLE_KEY'
export const FOCUS_PROPERTY_CLASS = 'FOCUS_PROPERTY_CLASS'
export const SHOW_PROPERTY_CLASS = 'SHOW_PROPERTY_CLASS'

export const SHOW_TREE = 'SHOW_TREE'
export const HIDE_TREE = 'HIDE_TREE'

export const SHOW_ALL_ASSOCIATED = 'SHOW_ALL_ASSOCIATED'
export const SHOW_RIGHT_HAND_SIDE = 'SHOW_RIGHT_HAND_SIDE'
export const SHOW_LEFT_HAND_SIDE = 'SHOW_LEFT_HAND_SIDE'

export const SHOW_LEGEND = 'SHOW_LEGEND'
export const SHOW_RELATION = 'SHOW_RELATION'

export const UPDATE_QUERY = 'UPDATE_QUERY'
export const PREV_CANDIDATE = 'PREV_CANDIDATE'
export const NEXT_CANDIDATE = 'NEXT_CANDIDATE'
export const SELECT_CANDIDATE = 'SELECT_CANDIDATE'
export const CONFIRM_CANDIDATE = 'CONFIRM_CANDIDATE'

export const SHOW_TOOLTIP = 'SHOW_TOOLTIP'
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP'

export const HIDE_PROPERTY_PANE = 'HIDE_PROPERTY_PANE'
export const HIDE_DETAIL_PANE = 'HIDE_DETAIL_PANE'
export const RESIZE = 'RESIZE'
