"""Add display_name and contact_uri

Revision ID: 16a59bb00069
Revises: e6f9efcfc37f
Create Date: 2019-07-30 18:53:04.505312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a59bb00069'
down_revision = 'e6f9efcfc37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_uri', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'contact_uri')
    # ### end Alembic commands ###
