"""Modify User

Revision ID: 5f713c0ac818
Revises: 4020005878ff
Create Date: 2019-07-11 15:59:26.380403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f713c0ac818'
down_revision = '4020005878ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=255), nullable=False))
    op.drop_index('email', table_name='users')
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
